Repository fdhhhdjd/Web-Online-School-Libary-Book, pull requests merged in 2023-01, with the labels that each got.

#55 Tai depops #4
  backend-manager-student/docker-compose.yml
  server-gateway/nginx/default.conf
  server-media-service/docker-compose.yml
  server-send-email-student/docker-compose.yml
  server-send-email-student/src/send_email_user/server.js
Labels: Success-Devops

#56 Developer
  backend-manager-student/docker-compose.yml
  server-gateway/nginx/default.conf
  server-media-service/docker-compose.yml
  server-send-email-student/docker-compose.yml
  server-send-email-student/src/send_email_user/server.js
Labels: Success-Devops

#57 Tai devops #45
  backend-manager-student/.gitignore
  backend-manager-student/docker-compose.yml
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.1.base.rdb
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.1.incr.aof
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.manifest
  backend-manager-student/redis-data/dump.rdb
Labels: DEV Processing

#58 Developer
  backend-manager-student/.gitignore
  backend-manager-student/docker-compose.yml
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.1.base.rdb
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.1.incr.aof
  backend-manager-student/redis-data/appendonlydir/appendonly.aof.manifest
  backend-manager-student/redis-data/dump.rdb
Labels: Success-Devops

#59 Tai devops #45
  makefile
  server-media-service/docker-compose.yml
Labels: DEV Processing

#60 Developer
  makefile
  server-media-service/docker-compose.yml
Labels: Success-Devops

#62 Developer
  backend-manager-student/docker-compose.yml
  makefile
  server-media-service/docker-compose.yml
  server-send-email-student/docker-compose.yml
Labels: DEV Processing

#64 #45 edit makefike run docker
  backend-manager-student/makefile
  makefile
  server-media-service/makefile
  server-send-email-student/makefile
Labels: DEV Processing

#66 #45 edit makefike run docker
  makefile
Labels: DEV Processing

#67 #45 edit makefike run docker
  makefile
Labels: DEV Processing

#70 #69 setup eslint and prettrc
  backend-manager-student/.eslintrc.js
  backend-manager-student/package.json
  server-media-service/.eslintrc.js
  server-media-service/package.json
  server-send-email-student/.eslintrc.js
  server-send-email-student/package.json
Labels: DEV Processing

#71 #69 setup eslint and prettrc
  backend-manager-student/.eslintrc.js
  backend-manager-student/package.json
  server-media-service/.eslintrc.js
  server-media-service/package.json
  server-send-email-student/.eslintrc.js
  server-send-email-student/package.json
Labels: DEV Processing

#72 #33 database
  backend-manager-student/.eslintrc.js
  backend-manager-student/migrations/init/20221227_create_table_user.sql
Labels: DEV Processing

#74 Developer
  backend-manager-student/.eslintrc.js
  backend-manager-student/migrations/init/20221227_create_table_user.sql
Labels: DEV Processing

#76 #4 nginx
  server-gateway/nginx/default.conf
Labels: Success-Devops

#78 #77 connect multiple Database
  backend-manager-student/.gitignore
  backend-manager-student/docker-compose.yml
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/server.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/db/init_multiple_redis.js
  backend-manager-student/src/share/db/redis_db.js
Labels: DEV Processing

#80 Developer
  backend-manager-student/.eslintrc.js
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/server.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/db/init_multiple_redis.js
  backend-manager-student/src/share/utils/redis-cluster-helper.js
Labels: Success-Frontend

#81 #69 unitest jest
  backend-manager-student/.jest/someModuleForTest.js
  backend-manager-student/jest.config.js
  backend-manager-student/test/v1/admin_api/request.admin.js
  backend-manager-student/test/v1/configs/constants.js
Labels: Success-Devops

#85 #83 system setup code
  backend-manager-student/.eslintrc.js
  backend-manager-student/package.json
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/admin_api/v1/routes/admin/admin.route.js
  backend-manager-student/src/admin_api/v1/routes/index.route.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/models/user.model.js
  backend-manager-student/src/share/patterns/LRU_Strategy.patterns.js
  backend-manager-student/src/user_api/app.js
  backend-manager-student/src/user_api/v1/controllers/user.controller.js
  backend-manager-student/src/user_api/v1/routes/index.router.js
  backend-manager-student/src/user_api/v1/routes/users/user.route.js
  package.json
Labels: Success-Devops

#87 #79 add code handle excel
  backend-manager-student/.gitignore
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/admin_api/v1/routes/admin/admin.route.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/middleware/handle_error.js
  backend-manager-student/src/share/services/admin.service.js
  backend-manager-student/src/share/utils/helper.js
Labels: Success-Backend

#89 #79 fix code excel
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/middleware/handle_error.js
  backend-manager-student/src/share/services/admin.service.js
  backend-manager-student/src/share/utils/helper.js
Labels: Success-Backend

#90 #13 setup vs code
  .vscode/settings.json
Labels: Success-Devops

#92 #88 edit build
  backend-manager-student/Dockerfile
  backend-manager-student/docker-compose.yml
  server-media-service/docker-compose.yml
  server-send-email-student/docker-compose.yml
Labels: Success-Devops

#93 #88 deploy edit makefile
  makefile
Labels: Success-Devops

#96 Developer
  backend-manager-student/.eslintrc.js
  backend-manager-student/makefile
  backend-manager-student/package-lock.json
  backend-manager-student/package.json
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/middleware/handle_error.js
  backend-manager-student/src/share/utils/helper.js
  makefile
  package-lock.json
  package.json
  server-media-service/makefile
  server-send-email-student/makefile
Labels: Success-Devops

#97 #75 create homepage and login page
  .vscode/settings.json
  backend-manager-student/migrations/init/20221227_create_table_user.sql
  frontend-manager-student/package-lock.json
  frontend-manager-student/package.json
  frontend-manager-student/public/index.html
  frontend-manager-student/src/App.js
  frontend-manager-student/src/assets/png/logo-school.png
  frontend-manager-student/src/assets/png/logo_tai_heo_dev.png
  frontend-manager-student/src/components/Layout/Layout.js
  frontend-manager-student/src/components/Layout/Layout.jsx
  frontend-manager-student/src/components/Layout/Navbar/index.jsx
  frontend-manager-student/src/components/Layout/Navbar/style.scss
  frontend-manager-student/src/components/Layout/Sidebar/index.jsx
  frontend-manager-student/src/components/Layout/Sidebar/style.scss
  frontend-manager-student/src/components/Layout/style.scss
  frontend-manager-student/src/imports/home_import/index.js
  frontend-manager-student/src/pages/Customer/Auth/Login/index.jsx
  frontend-manager-student/src/pages/Customer/Auth/Login/style.scss
  frontend-manager-student/src/pages/Customer/Home/index.jsx
  frontend-manager-student/src/pages/Customer/Home/style.scss
  frontend-manager-student/src/pages/Home/Home.js
  frontend-manager-student/src/pages/Home/components/TabHome.js
  frontend-manager-student/src/routers/index.js
  frontend-manager-student/src/styles/Home_Style/Home.css
  frontend-manager-student/src/styles/_animation.scss
  frontend-manager-student/src/styles/_mixin.scss
  frontend-manager-student/src/styles/_typography.scss
  frontend-manager-student/src/styles/_variable.scss
  frontend-manager-student/src/styles/body.scss
  frontend-manager-student/src/styles/style.scss
  frontend-manager-student/src/tests/auth_test/login.test.js
  package-lock.json
Labels: DEV Processing

#98 Developer
  .vscode/settings.json
  backend-manager-student/migrations/init/20221227_create_table_user.sql
  frontend-manager-student/package-lock.json
  frontend-manager-student/package.json
  frontend-manager-student/public/index.html
  frontend-manager-student/src/App.js
  frontend-manager-student/src/assets/png/logo-school.png
  frontend-manager-student/src/assets/png/logo_tai_heo_dev.png
  frontend-manager-student/src/components/Layout/Layout.js
  frontend-manager-student/src/components/Layout/Layout.jsx
  frontend-manager-student/src/components/Layout/Navbar/index.jsx
  frontend-manager-student/src/components/Layout/Navbar/style.scss
  frontend-manager-student/src/components/Layout/Sidebar/index.jsx
  frontend-manager-student/src/components/Layout/Sidebar/style.scss
  frontend-manager-student/src/components/Layout/style.scss
  frontend-manager-student/src/imports/home_import/index.js
  frontend-manager-student/src/pages/Customer/Auth/Login/index.jsx
  frontend-manager-student/src/pages/Customer/Auth/Login/style.scss
  frontend-manager-student/src/pages/Customer/Home/index.jsx
  frontend-manager-student/src/pages/Customer/Home/style.scss
  frontend-manager-student/src/pages/Home/Home.js
  frontend-manager-student/src/pages/Home/components/TabHome.js
  frontend-manager-student/src/routers/index.js
  frontend-manager-student/src/styles/Home_Style/Home.css
  frontend-manager-student/src/styles/_animation.scss
  frontend-manager-student/src/styles/_mixin.scss
  frontend-manager-student/src/styles/_typography.scss
  frontend-manager-student/src/styles/_variable.scss
  frontend-manager-student/src/styles/body.scss
  frontend-manager-student/src/styles/style.scss
  frontend-manager-student/src/tests/auth_test/login.test.js
  package-lock.json
Labels: Success-Frontend

#99 #75 package-lock frontend
  frontend-manager-student/package-lock.json
Labels: Success-Frontend

#100 #40 add prod makefile
  backend-manager-student/makefile
  makefile
  server-media-service/makefile
  server-send-email-student/makefile
Labels: Success-Devops

#101 #95 backend
  backend-manager-student/.eslintrc.js
  backend-manager-student/docker-compose.yml
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/server.js
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/configs/regex.js
  backend-manager-student/src/share/db/init_multiple_redis.js
  backend-manager-student/src/share/db/posgresql.js
  backend-manager-student/src/share/db/postgresql.js
  backend-manager-student/src/share/models/user.model.js
  backend-manager-student/src/share/patterns/LRU_Strategy.patterns.js
  backend-manager-student/src/share/utils/helper.js
  backend-manager-student/src/share/utils/password.js
  backend-manager-student/src/share/utils/random.js
  backend-manager-student/src/user_api/app.js
Labels: Success-Backend

#102 #95 backend
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/server.js
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/configs/regex.js
  backend-manager-student/src/share/db/init_multiple_redis.js
  backend-manager-student/src/share/db/postgresql.js
  backend-manager-student/src/share/patterns/LRU_Strategy.patterns.js
  backend-manager-student/src/share/utils/random.js
  backend-manager-student/src/user_api/app.js
Labels: Success-Backend

#103 #95 backend setup
  backend-manager-student/.eslintrc.js
  backend-manager-student/package.json
  backend-manager-student/src/share/configs/config.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/middleware/handle_error.js
  backend-manager-student/src/share/models/user.model.js
  backend-manager-student/src/share/utils/helper.js
  backend-manager-student/src/share/utils/random.js
  backend-manager-student/src/share/utils/redis-cluster-helper.js
  backend-manager-student/src/user_api/v1/controllers/user.controller.js
Labels: Success-Backend

#105 #104 setup scrip and edit docker
  .gitignore
  backend-manager-student/.gitignore
  backend-manager-student/docker-compose-dev.yml
  backend-manager-student/docker-compose.yml
  backend-manager-student/dockerfile.redis
  backend-manager-student/dockerfile.redis.dev
  backend-manager-student/logs/logrotate.conf
  backend-manager-student/migrations/init/20221227_create_table_user.sql
  backend-manager-student/scrip/scrip_redis.sh
  backend-manager-student/src/share/middleware/handle_error.js
  backend-manager-student/src/share/models/user.model.js
  backend-manager-student/src/share/utils/helper.js
  backend-manager-student/src/share/utils/redis-cluster-helper.js
  server-gateway/nginx/Dockerfile.dev
Labels: Success-Devops

#107 #106 setup and add srouce swagger
  backend-manager-student/docker-compose-dev.yml
  backend-manager-student/package.json
  backend-manager-student/src/admin_api/app.js
  backend-manager-student/src/admin_api/server.js
  backend-manager-student/src/admin_api/v1/Swagger/admin_api/admin.swagger.yaml
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/configs/option.js
  backend-manager-student/src/user_api/app.js
  backend-manager-student/src/user_api/v1/Swagger/user_api/user.swagger.yaml
Labels: Success-Backend

#108 #106 add media and swagger
  server-media-service/docker-compose-dev.yml
  server-media-service/package.json
  server-media-service/src/media-service/app.js
  server-media-service/src/media-service/v1/Swagger/media_api/media.swagger.yaml
  server-media-service/src/media-service/v1/controllers/upload.controller.js
  server-media-service/src/share/configs/config.js
  server-media-service/src/share/configs/constants.js
  server-media-service/src/share/configs/option.js
  server-media-service/src/share/services/upload.service.js
  server-media-service/src/share/utils/storage.js
Labels: Success-Backend

#109 #79 read excel cloud
  backend-manager-student/.gitignore
  backend-manager-student/package.json
  backend-manager-student/setup/redis.conf
  backend-manager-student/src/admin_api/v1/controllers/admin.controller.js
  backend-manager-student/src/share/configs/constants.js
  backend-manager-student/src/share/utils/helper.js
Labels: Success-Backend

#111 #104 scrip edit logrotate
  backend-manager-student/.gitignore
  backend-manager-student/docker-compose-dev.yml
  backend-manager-student/docker-compose.yml
  backend-manager-student/dockerfile.redis
Labels: Success-Devops
